// client/src/lib/drafts.api.ts
import { get, post } from "./api";
import { Draft as DraftSchema, type TDraft } from "../../../shared/contracts";

/**
 * List all message drafts (email + SMS) generated by the agent.
 * Backed by GET /api/drafts
 */
export async function fetchDrafts(): Promise<TDraft[]> {
  // Zod-validated response
  return get("/drafts", DraftSchema.array());
}

/**
 * Approve a draft and trigger send (Postmark/Twilio), then mark SENT.
 * Backed by POST /api/agent/drafts/:id/approve
 */
export async function approveDraft(id: string): Promise<{ ok: true }> {
  await post(`/agent/drafts/${id}/approve`);
  return { ok: true };
}
